### ISSUE TITLE
TypeError:  is not JSON serializable

### ISSUE THREAD

**Issue by Hiieu** [brack3t/Djrill#100]
```
TypeError: <django.utils.functional.__proxy__ object at 0x030B1D30> is not JSON serializable in a Djrill message (perhaps it's a merge var?). Try converting i  t to a string or number first. 
```

What does it mean?

**Comment by medmunds** [comment]
The "not JSON serializable" error means one of the options you've set on your EmailMessage is an unexpected type, and Djrill doesn't know how to convert it to something Mandrill will understand. So you'll need to convert it to a string yourself, when you set the option.

This commonly occurs with merge variables, but it could be any option you're setting. (We'd need to see the part of your code that's creating and sending the message to say more.)

`django.utils.functional.__proxy__` *probably* means the issue is with an option being set to a lazy string translation ([ugettext_lazy](https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#lazy-translations)). If that's the problem, you can probably fix it by switching to the non-lazy version of [ugettext](https://docs.djangoproject.com/en/1.8/topics/i18n/translation/#standard-translation).

**Comment by Hiieu** [comment]
Yes that was it, thanks.
