### ISSUE TITLE
Mandrill templates not working with django-mailer

### ISSUE THREAD

**Issue by OxanaSachenkova** [brack3t/Djrill#83]
When using django-mailer queue as the email backend, email message attribute template_name isn't saved, so djrill fails to use the correct mandrill API call and uses a regular send method without using the template. 

My settings:
EMAIL_BACKEND = 'django_mailer.smtp_queue.EmailBackend'
MAILER_EMAIL_BACKEND = 'djrill.mail.backends.djrill.DjrillBackend'

When using djrill as EMAIL_BACKEND directly, it works fine. 

Would be great to add full support of django-mailer.

**Comment by medmunds** [comment]
It sounds like you're actually using [django-mailer-2][django-mailer-2] (a.k.a. "django_mailer", with an underscore) -- not [django-mailer][django-mailer] (with a hyphen).

Django-mailer-2 is architected to work with an SMTP backend, not a backend that calls a web service like Djrill does. Django-mailer-2 queues a message by flattening it to an RFC822 message string and storing that in the DB. But that message string won't have any of Djrill's custom properties, so this will never work with Djrill. (And there's not really much we could do in Djrill to solve this.)

Django-mailer, on the other hand, pickles the original EmailMessage object and stores that in the DB to queue the message. This works just fine with Djrill, because the unpickled object at send time retains all of the original custom properties.

You have a couple of options:

1. If you want to keep using django-mailer-2, don't use Djrill. Instead, point django-mailer-2 directly at Mandrill's SMTP server, and use [Mandrill's custom SMTP headers][mandrill-smtp-headers] to specify templates and other Mandrill options.

2. If you want to keep using Djrill, don't use django-mailer-2. Instead, switch to [django-mailer][django-mailer]. Django-mailer's email backend will handle Djrill EmailMessage objects properly. (I've been using this combination successfully for a couple of years now on a site I run.)

One caveat on django-mailer: if you want to use its DontSendEntry blacklist, that's _not_ enforced in its backend (only in django-mailer's send_mail and similar functions, oddly). So the blacklist won't apply if you use EmailMessage.send(). (This isn't specific to Djrill -- it applies to any usage of django-mailer.) Here's a gist with the function I use to [queue a message into django-mailer][queue_message] while enforcing the DontSendEntry blacklist.

[django-mailer]: https://github.com/pinax/django-mailer
[django-mailer-2]: http://django-mailer2.readthedocs.org/
[mandrill-smtp-headers]: http://help.mandrill.com/entries/21688056-Using-SMTP-Headers-to-customize-your-messages
[queue_message]: https://gist.github.com/medmunds/45ab7efc79e2d71ad514

**Comment by OxanaSachenkova** [comment]
@medmunds Thank you for such elaborate answer!
